### ISSUE TITLE
[Drop down list] Small glitch

### ISSUE THREAD

**Issue by 121sim** [xot/tagger#1]
As an addition to your limitation and the filled bug of un-hilighting options in the drop won list, there seems to be a small glitch of partial text as below (maybe related) :

![tagger](https://github.com/xot/tagger/assets/74899182/5aa681f5-c95e-4878-9576-aaaac09ed1a2)

Thanks for your work.

**Comment by xot** [comment]
Hm.. don't know how to fix this. Happy to report that in TB 128 the choice in the dropdown list is now properly highlighted.
