### ISSUE TITLE
Copy and paste the tags

### ISSUE THREAD

**Issue by hastelloy** [xot/tagger#2]
Nice add-on for user like to manage email messages with tags...
Would it be possible to have the function to copy and paste tags from one message to another? 
This would be very useful for adding tags to messages for the same conversation topic.

**Comment by xot** [comment]
Yeah, was thing about this. Or even add them automatically for a new message in a conversation (like Postbox does). It's on the todo list.

**Comment by xot** [comment]
Configuration option added to tag new incoming messages with the tags assigned to the messages it replies to.
