### ISSUE TITLE
Problem with non-English tags

### ISSUE THREAD

**Issue by alexanderd24** [xot/tagger#3]
It seems that the extension doesn't work correctly with non-English tags (Russian, to be more specific). I can't create tag with only Russian letters in it. If I add any English letter to the Russian tag it works just fine.
I'm using TB 115.11.0 and Tagger 1.2.

**Comment by xot** [comment]
Thank you for flagging this bug. I have to think about a possible fix. For the moment, what should work is *first* create the tag once using the normal Thunderbird interface (Message > Tag > New Tag...) , and then you should be able to tag your messages with Tagger normally.

**Comment by xot** [comment]
This has now been fixed partially - but unfortunately not in a  way compatible with how Thunderbird itself deals with non-ASCII tags (though the manage tags interface).
