### ISSUE TITLE
Tagger interface not shown, but is there

### ISSUE THREAD

**Issue by equaeghe** [xot/tagger#7]
I've installed tagger in Thunderbird 128.3.1esr. Almost always when I try to use it, the interface is not visible. Instead, there is a white box. However, if I then interact with the white box as if the interface was there, it does work. Please see the screenshot below:
![Schermafdruk_20241023_094841](https://github.com/user-attachments/assets/6142bc18-eac7-49bf-adf6-d60ac6b32ab1)
I have actually seen the interface twice (in about 25 trials), but then it quickly disappeared again.

_I guess I will need to provide more information. Please let me know how to gather it. (Using Thunderbird itself or, e.g., from my system logs.)_

(I have another addon installed (Tag Popup) which has the same issue, so it may be related to my installation or that addon may have the same issue.)

**Comment by xot** [comment]
I've never seen this and wouldn't know how to  debug this. I seem to remember you had issues with the preferences pane also not displaying properly for you. These issues might be related, and could be caused by your setup somehow.

**Comment by equaeghe** [comment]
This has automagically resolved itself. Namely, the problem is gone and I do not know what fixed it.
