### ISSUE TITLE
Question: Width Adjustment

### ISSUE THREAD

**Issue by infinitelyintrigued** [xot/tagger#8]
Hi, I've started using this add-on and find it very useful.

I have tags with rather long names. Is there a way to adjust the width of the tag name textbox?

If not, is it possible make Tagger to show the complete name when the mouse pointer is moved over the name?

Thank you

**Comment by xot** [comment]
Unfortunately the width cannot be dynamically adjusted to the longest tag, but  I've increased the fixed with to 40 characters.
